{% set version = "28.2.0" %}

package:
  name: kubernetes_asyncio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kubernetes_asyncio/kubernetes_asyncio-{{ version }}.tar.gz
  sha256: 9399790ea4a41fafd5cef4017e1d8dc3e16502fe16825be0bb4f07a6deb05345

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp >=3.7.0,<4.0.0
    - certifi >=14.05.14
    - python-dateutil >=2.5.3
    - pyyaml >=3.12
    - setuptools >=21.0.0
    - six >=1.9.0
    - urllib3 >=1.24.2

test:
  imports:
    - kubernetes_asyncio
    - kubernetes_asyncio.client
    - kubernetes_asyncio.client.api
    - kubernetes_asyncio.client.models
    - kubernetes_asyncio.config
    - kubernetes_asyncio.stream
    - kubernetes_asyncio.utils
    - kubernetes_asyncio.watch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tomplus/kubernetes_asyncio
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Kubernetes asynchronous python client

extra:
  recipe-maintainers:
    - ocefpaf
